# Generated by Django 4.1.7 on 2023-02-26 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
