# Generated by Django 4.1.7 on 2023-02-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='date_created',
            new_name='created',
        ),
    ]
