# Generated by Django 4.1.7 on 2023-02-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_author_options_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.PositiveBigIntegerField()),
                ('created', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
    ]
