# Generated by Django 4.1.7 on 2023-02-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='blog',
            field=models.ManyToManyField(to='app.blog'),
        ),
    ]
