# Generated by Django 4.1.7 on 2023-02-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_testt_alter_school_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=32, unique=True),
        ),
    ]
